import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import { fetchCategories } from "@/fetch/articleCategories.fetch";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Load font at module scope
const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-montserrat",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
    const categories: any[] = await fetchCategories();
  return (
    <html lang="en" className={montserrat.variable}>
      <body className={montserrat.className}>
        <Header />
        {children}
        {/* <div className="min-h-svh">{children}</div> */}
        <Footer categories={categories}/>
      </body>
    </html>
  );
}
